// Generated by statecraft codegen client. Do not edit.

export type EntityName = "User" | "Todo";

export const ENTITIES: EntityName[] = ["User", "Todo"];

export interface User {
  id: string;
  email: string;
  displayName: string;
  createdAt: string;
}

export interface Todo {
  id: string;
  title: string;
  done: boolean;
  authorId: string;
  createdAt: string;
}

export type QueryName = "todosByAuthor" | "allTodos" | "todoById";

export const QUERIES: QueryName[] = ["todosByAuthor", "allTodos", "todoById"];

export interface TodosByAuthorInput {
  authorId: string;
}

export interface AllTodosInput {
  done?: boolean;
}

export interface TodoByIdInput {
  todoId: string;
}

export type ActionName = "createTodo" | "toggleTodo";

export const ACTIONS: ActionName[] = ["createTodo", "toggleTodo"];

export interface CreateTodoInput {
  title: string;
  authorId: string;
}

export interface ToggleTodoInput {
  todoId: string;
}

// ---------------------------------------------------------------------------
// Runtime client
// ---------------------------------------------------------------------------

const DEFAULT_BASE_URL = "http://localhost:4321";

async function _request(baseUrl: string, method: string, path: string, body?: unknown, token?: string): Promise<unknown> {
  const headers: Record<string, string> = {};
  if (body) headers["Content-Type"] = "application/json";
  if (token) headers["Authorization"] = `Bearer ${token}`;
  const res = await fetch(`${baseUrl}${path}`, {
    method,
    headers,
    body: body ? JSON.stringify(body) : undefined,
  });
  if (!res.ok) {
    const err = await res.json().catch(() => ({})) as Record<string, unknown>;
    const errorObj = err?.error as Record<string, unknown> | undefined;
    throw new Error((errorObj?.message as string) ?? `HTTP ${res.status}`);
  }
  return res.json();
}

export interface AgentDBClient {
  list(entity: EntityName): Promise<Record<string, unknown>[]>;
  get(entity: EntityName, id: string): Promise<Record<string, unknown> | null>;
  insert(entity: EntityName, data: Record<string, unknown>): Promise<{ id: string }>;
  update(entity: EntityName, id: string, data: Record<string, unknown>): Promise<{ updated: boolean }>;
  remove(entity: EntityName, id: string): Promise<{ deleted: boolean }>;
  action(name: ActionName, input: Record<string, unknown>): Promise<ActionResult>;
  actions: Actions;
}

export interface ActionResult {
  action: string;
  input: Record<string, unknown>;
  executed: boolean;
}

export interface Actions {
  createTodo(input: CreateTodoInput): Promise<ActionResult>;
  toggleTodo(input: ToggleTodoInput): Promise<ActionResult>;
}

export function createClient(baseUrl: string = DEFAULT_BASE_URL, token?: string): AgentDBClient {
  const req = (method: string, path: string, body?: unknown) => _request(baseUrl, method, path, body, token);

  const actions: Actions = {
    createTodo: (input) => req("POST", "/api/actions/createTodo", input) as Promise<ActionResult>,
    toggleTodo: (input) => req("POST", "/api/actions/toggleTodo", input) as Promise<ActionResult>,
  };

  return {
    list: (entity) => req("GET", `/api/entities/${entity}`) as Promise<Record<string, unknown>[]>,
    get: (entity, id) => req("GET", `/api/entities/${entity}/${id}`).then(r => r as Record<string, unknown>).catch(() => null),
    insert: (entity, data) => req("POST", `/api/entities/${entity}`, data) as Promise<{ id: string }>,
    update: (entity, id, data) => req("PATCH", `/api/entities/${entity}/${id}`, data) as Promise<{ updated: boolean }>,
    remove: (entity, id) => req("DELETE", `/api/entities/${entity}/${id}`) as Promise<{ deleted: boolean }>,
    action: (name, input) => req("POST", `/api/actions/${name}`, input) as Promise<ActionResult>,
    actions,
  };
}

// ---------------------------------------------------------------------------
// Server Actions (Next.js App Router compatible)
// ---------------------------------------------------------------------------

/** Create a server-side client for use in Next.js Server Actions / RSC. */
export function createServerClient(
  baseUrl: string = process.env.STATECRAFT_URL ?? DEFAULT_BASE_URL,
  token?: string
): AgentDBClient {
  return createClient(baseUrl, token);
}

// ---------------------------------------------------------------------------
// React 19 use() compatible promises
// ---------------------------------------------------------------------------

/** Pre-fetch data as a promise for React 19 use() hook. */
export function prefetch(client: AgentDBClient, entity: EntityName): Promise<Record<string, unknown>[]> {
  return client.list(entity);
}

/** Pre-fetch a single row for React 19 use() hook. */
export function prefetchOne(client: AgentDBClient, entity: EntityName, id: string): Promise<Record<string, unknown> | null> {
  return client.get(entity, id);
}
