use pylon_kernel::{Diagnostic, ExitCode, Severity};

use crate::manifest::{load_manifest, validate_all};
use crate::output::{print_diagnostics, print_json};

// ---------------------------------------------------------------------------
// Deployment target
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, PartialEq, Eq)]
enum DeployTarget {
    /// Just the manifest + client bindings + static pages — no IaaS
    /// integration. Renamed from "Default" once `pylon deploy` started
    /// defaulting to --target cloud; this one's now an opt-in via
    /// `--target manifest`.
    Manifest,
    /// Generate a Dockerfile.
    Docker,
    /// Generate a Dockerfile + fly.toml.
    Fly,
    /// Generate a docker-compose.yml + Dockerfile.
    Compose,
    /// Generate a Cloudflare Workers wrangler.toml. Experimental — see
    /// crates/workers/README.md for what works.
    Workers,
    /// Generate a systemd unit file for VPS deploys.
    Systemd,
}

impl DeployTarget {
    fn from_arg(s: &str) -> Option<Self> {
        match s {
            "manifest" => Some(Self::Manifest),
            "docker" => Some(Self::Docker),
            "fly" => Some(Self::Fly),
            "compose" => Some(Self::Compose),
            "workers" => Some(Self::Workers),
            "systemd" => Some(Self::Systemd),
            _ => None,
        }
    }
}

// ---------------------------------------------------------------------------
// File generators
// ---------------------------------------------------------------------------

/// Marker line present in every file this command generates. Lets a re-run
/// distinguish "our file from a previous run" (safe to regenerate) from a
/// hand-written file (never clobbered).
const GENERATED_MARKER: &str = "Generated by `pylon deploy`";

fn generate_dockerfile() -> String {
    let version = env!("CARGO_PKG_VERSION");
    format!(
        r#"# {GENERATED_MARKER} — edit freely; remove this line to stop regeneration.
# The base image bundles the pylon binary + Bun (for TypeScript functions
# and SSR). Your app source is copied in and served with `pylon start`.
#
# Build:  docker build -t my-app .
# Run:    docker run -p 4321:4321 -v pylon-data:/data my-app
FROM ghcr.io/pylonsync/pylon:{version}

WORKDIR /app
# Dependencies first so Docker caches the install layer across code changes.
COPY --chown=pylon:pylon package.json bun.lock* package-lock.json* ./
RUN bun install
COPY --chown=pylon:pylon . .

# The base image defaults to PYLON_DEV_MODE=true so the container boots
# with zero config. For production, set (via --env / your platform's secrets):
#   PYLON_DEV_MODE=false
#   PYLON_ADMIN_TOKEN=<64+ random hex bytes>
#   PYLON_CORS_ORIGIN=https://your-app.example.com   (or manifest.auth.trustedOrigins)

# SQLite DB, uploads, and sessions live on the /data volume (declared by
# the base image). CMD is inherited: ["pylon", "start", "app.ts"]
"#
    )
}

fn generate_dockerignore() -> String {
    format!(
        r#"# {GENERATED_MARKER}
node_modules
.pylon
.git
deploy
dist
*.db
.env*
"#
    )
}

fn generate_fly_toml(app_name: &str) -> String {
    format!(
        r#"# {GENERATED_MARKER} — edit freely; remove this line to stop regeneration.
app = "{app_name}"
primary_region = "iad"

[http_service]
  internal_port = 4321
  force_https = true

[build]
  dockerfile = "Dockerfile"

[mounts]
  source = "pylon_data"
  destination = "/data"
"#
    )
}

fn generate_wrangler_toml(app_name: &str) -> String {
    format!(
        r#"name = "{app_name}"
main = "build/worker.js"
compatibility_date = "2025-01-01"

# Created database with: wrangler d1 create {app_name}-db
# Then paste the database_id printed by wrangler below.
[[d1_databases]]
binding = "PYLON_DB"
database_name = "{app_name}-db"
database_id = "REPLACE_WITH_D1_DATABASE_ID"

# Optional: persistent file storage via R2
# [[r2_buckets]]
# binding = "PYLON_FILES"
# bucket_name = "{app_name}-files"

# Per-room WebSocket Durable Object (experimental)
# [[durable_objects.bindings]]
# name = "ROOM"
# class_name = "RoomDO"
"#
    )
}

fn generate_systemd_unit(app_name: &str) -> String {
    format!(
        r#"# {GENERATED_MARKER} — edit freely; remove this line to stop regeneration.
#
# Assumes:
#   - the pylon binary at /usr/local/bin/pylon
#   - bun at /usr/local/bin/bun (needed for TypeScript functions + SSR;
#     install with: curl -fsSL https://bun.sh/install | BUN_INSTALL=/usr/local bash)
#   - your app source (app.ts, functions/, app/, node_modules) at /opt/{app_name}
#     (run `bun install` there after each code update)
#   - writable data dir at /var/lib/pylon
[Unit]
Description=pylon ({app_name})
After=network-online.target

[Service]
Type=simple
User=pylon
Group=pylon
WorkingDirectory=/opt/{app_name}
ExecStart=/usr/local/bin/pylon start app.ts
Restart=on-failure
RestartSec=5

# Hardening
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=/var/lib/pylon

# Environment
Environment=PYLON_PORT=4321
Environment=PYLON_DB_PATH=/var/lib/pylon/pylon.db
Environment=PYLON_FILES_DIR=/var/lib/pylon/uploads
Environment=PYLON_SESSION_DB=/var/lib/pylon/sessions.db
Environment=PYLON_DEV_MODE=false
# Non-dev mode requires trusted origins: set manifest.auth.trustedOrigins in
# app.ts, or PYLON_CORS_ORIGIN here. PYLON_ADMIN_TOKEN belongs in the
# EnvironmentFile below, not inline in the unit.
# Environment=PYLON_CORS_ORIGIN=https://your-app.example.com
# EnvironmentFile=/etc/pylon/secrets  # PYLON_ADMIN_TOKEN, OAuth keys, etc.

[Install]
WantedBy=multi-user.target
"#
    )
}

fn generate_docker_compose() -> String {
    format!(
        r#"# {GENERATED_MARKER} — edit freely; remove this line to stop regeneration.
services:
  app:
    build: .
    ports:
      - "4321:4321"
    environment:
      - DATABASE_URL=postgres://pylon:pylon@db:5432/pylon
      - PYLON_ADMIN_TOKEN=${{PYLON_ADMIN_TOKEN}}
    volumes:
      - pylon-data:/data
    depends_on:
      db:
        condition: service_started

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=pylon
      - POSTGRES_PASSWORD=pylon
      - POSTGRES_DB=pylon
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pylon-data:
  pgdata:
"#
    )
}

// ---------------------------------------------------------------------------
// Command entry point
// ---------------------------------------------------------------------------

pub fn run(args: &[String], json_mode: bool) -> ExitCode {
    // Default target is `cloud` — the hosted deploy path is what
    // `pylon deploy` (no flag) means today. File-generation targets
    // (docker / fly / compose / workers / systemd / manifest) are
    // explicit opt-ins. Short-circuit before any manifest load so we
    // don't waste cycles serializing what the cloud's about to
    // rebuild anyway.
    let target_raw = args
        .windows(2)
        .find(|w| w[0] == "--target")
        .map(|w| w[1].as_str());
    if target_raw.is_none() || target_raw == Some("cloud") {
        return crate::commands::deploy_cloud::run(args, json_mode);
    }

    // Collect positionals, skipping flag VALUES as well as flags — without
    // this, `--target docker` fed "docker" in as the manifest path and the
    // command failed with MANIFEST_READ_FAILED on every split-form invocation.
    let value_flags = ["--target", "--out"];
    let mut positional: Vec<&str> = Vec::new();
    let mut skip_next = false;
    for a in args {
        if skip_next {
            skip_next = false;
            continue;
        }
        if value_flags.contains(&a.as_str()) {
            skip_next = true;
            continue;
        }
        if a.starts_with('-') || a == "deploy" {
            continue;
        }
        positional.push(a.as_str());
    }

    let manifest_path = positional.first().copied().unwrap_or("pylon.manifest.json");

    let out_dir = args
        .windows(2)
        .find(|w| w[0] == "--out")
        .map(|w| w[1].as_str())
        .unwrap_or("deploy");

    // target_raw is guaranteed Some here (the is_none() short-circuit
    // above returned). Validate it parses to a known file-generation
    // target.
    let raw = target_raw.expect("checked above");
    let target = match DeployTarget::from_arg(raw) {
        Some(t) => t,
        None => {
            print_diagnostics(
                &[Diagnostic {
                    severity: Severity::Error,
                    code: "INVALID_TARGET".into(),
                    message: format!(
                        "Unknown deploy target \"{raw}\". Valid targets: cloud, docker, fly, compose, workers, systemd, manifest"
                    ),
                    span: None,
                    hint: Some(
                        "Default (no flag) deploys to Pylon Cloud. Use --target docker|fly|compose|workers|systemd to generate IaaS config, or --target manifest for just the bindings.".into(),
                    ),
                }],
                json_mode,
            );
            return ExitCode::Error;
        }
    };

    let manifest = match load_manifest(manifest_path) {
        Ok(m) => m,
        Err(diags) => {
            print_diagnostics(&diags, json_mode);
            return ExitCode::Error;
        }
    };

    let diagnostics = validate_all(&manifest);
    let has_errors = diagnostics.iter().any(|d| d.severity == Severity::Error);

    if has_errors {
        print_diagnostics(&diagnostics, json_mode);
        return ExitCode::Error;
    }

    // Create deploy directory.
    let out_path = std::path::Path::new(out_dir);
    if let Err(e) = std::fs::create_dir_all(out_path) {
        print_diagnostics(
            &[Diagnostic {
                severity: Severity::Error,
                code: "DEPLOY_DIR_FAILED".into(),
                message: format!("Could not create deploy directory: {e}"),
                span: None,
                hint: None,
            }],
            json_mode,
        );
        return ExitCode::Error;
    }

    // Write manifest to deploy dir.
    let manifest_out = out_path.join("pylon.manifest.json");
    let manifest_json = serde_json::to_string_pretty(&manifest).unwrap_or_default();
    if let Err(e) = std::fs::write(&manifest_out, format!("{manifest_json}\n")) {
        print_diagnostics(
            &[Diagnostic {
                severity: Severity::Error,
                code: "DEPLOY_WRITE_FAILED".into(),
                message: format!("Could not write manifest: {e}"),
                span: None,
                hint: None,
            }],
            json_mode,
        );
        return ExitCode::Error;
    }

    // Write client bindings.
    let client_ts = crate::client_codegen::generate_client_ts(&manifest);
    let _ = std::fs::write(out_path.join("pylon.client.ts"), &client_ts);

    // Generate static pages if any.
    let static_pages = pylon_staticgen::generate_static_pages(&manifest);
    if !static_pages.is_empty() {
        let static_dir = out_path.join("static");
        let _ = pylon_staticgen::write_pages(&static_pages, &static_dir);
    }

    // Write a small deploy info file.
    let deploy_info = serde_json::json!({
        "name": manifest.name,
        "version": manifest.version,
        "manifest_version": manifest.manifest_version,
        "entities": manifest.entities.len(),
        "queries": manifest.queries.len(),
        "actions": manifest.actions.len(),
        "policies": manifest.policies.len(),
        "routes": manifest.routes.len(),
        "static_pages": static_pages.len(),
    });
    let _ = std::fs::write(
        out_path.join("deploy.json"),
        serde_json::to_string_pretty(&deploy_info).unwrap_or_default(),
    );

    // -----------------------------------------------------------------------
    // Target-specific file generation
    // -----------------------------------------------------------------------

    let mut generated_files: Vec<String> = vec![
        "pylon.manifest.json".into(),
        "pylon.client.ts".into(),
        "deploy.json".into(),
    ];

    // Docker-ecosystem files (Dockerfile, .dockerignore, fly.toml,
    // docker-compose.yml) go to the PROJECT ROOT, not out_dir: `docker
    // build`, `fly launch`, and `docker compose up` all need the app
    // source as their build context, and deploy/ only holds the manifest
    // + bindings. Hand-written files are never clobbered (see
    // write_root_artifact).
    let root_path = std::path::Path::new(manifest_path)
        .parent()
        .filter(|p| !p.as_os_str().is_empty())
        .unwrap_or_else(|| std::path::Path::new("."))
        .to_path_buf();

    match target {
        DeployTarget::Docker => {
            write_root_artifact(
                &root_path,
                "Dockerfile",
                &generate_dockerfile(),
                json_mode,
                &mut generated_files,
            );
            write_root_artifact(
                &root_path,
                ".dockerignore",
                &generate_dockerignore(),
                json_mode,
                &mut generated_files,
            );
        }
        DeployTarget::Fly => {
            write_root_artifact(
                &root_path,
                "Dockerfile",
                &generate_dockerfile(),
                json_mode,
                &mut generated_files,
            );
            write_root_artifact(
                &root_path,
                ".dockerignore",
                &generate_dockerignore(),
                json_mode,
                &mut generated_files,
            );

            let app_name = sanitize_app_name(&manifest.name);
            write_root_artifact(
                &root_path,
                "fly.toml",
                &generate_fly_toml(&app_name),
                json_mode,
                &mut generated_files,
            );
        }
        DeployTarget::Compose => {
            write_root_artifact(
                &root_path,
                "Dockerfile",
                &generate_dockerfile(),
                json_mode,
                &mut generated_files,
            );
            write_root_artifact(
                &root_path,
                ".dockerignore",
                &generate_dockerignore(),
                json_mode,
                &mut generated_files,
            );
            write_root_artifact(
                &root_path,
                "docker-compose.yml",
                &generate_docker_compose(),
                json_mode,
                &mut generated_files,
            );
        }
        DeployTarget::Workers => {
            let app_name = sanitize_app_name(&manifest.name);
            let wrangler = generate_wrangler_toml(&app_name);
            write_or_fail(out_path, "wrangler.toml", &wrangler, json_mode);
            generated_files.push("wrangler.toml".into());
        }
        DeployTarget::Systemd => {
            let app_name = sanitize_app_name(&manifest.name);
            let unit = generate_systemd_unit(&app_name);
            write_or_fail(out_path, "pylon.service", &unit, json_mode);
            generated_files.push("pylon.service".into());
        }
        DeployTarget::Manifest => {}
    }

    // -----------------------------------------------------------------------
    // Output
    // -----------------------------------------------------------------------

    if json_mode {
        print_json(&serde_json::json!({
            "code": "DEPLOY_OK",
            "out_dir": out_dir,
            "manifest": manifest_path,
            "target": format!("{target:?}"),
            "static_pages": static_pages.len(),
            "files": generated_files,
        }));
    } else {
        println!("Deploy package created: {out_dir}/");
        for f in &generated_files {
            println!("  {f}");
        }
        if !static_pages.is_empty() {
            println!("  static/ ({} pages)", static_pages.len());
        }
        println!();

        match target {
            DeployTarget::Docker => {
                println!("To build and run (from the project root):");
                println!("  docker build -t pylon-app .");
                println!("  docker run -p 4321:4321 -v pylon-data:/data pylon-app");
            }
            DeployTarget::Fly => {
                println!("To deploy to Fly.io (from the project root):");
                println!("  fly launch");
            }
            DeployTarget::Compose => {
                println!("To run with Docker Compose (from the project root):");
                println!("  docker compose up --build");
            }
            DeployTarget::Workers => {
                println!("To deploy to Cloudflare Workers (experimental):");
                println!("  cd {out_dir}");
                println!("  wrangler d1 create $(basename $(pwd))-db");
                println!("  # paste database_id into wrangler.toml");
                println!("  wrangler deploy");
                println!();
                println!("See crates/workers/README.md for current limitations.");
            }
            DeployTarget::Systemd => {
                let app_name = sanitize_app_name(&manifest.name);
                println!("To install on a Linux VPS:");
                println!("  # binary + bun (bun runs your TypeScript functions + SSR)");
                println!("  curl -fsSL https://www.pylonsync.com/install.sh | sudo PYLON_INSTALL=/usr/local bash");
                println!("  curl -fsSL https://bun.sh/install | sudo BUN_INSTALL=/usr/local bash");
                println!("  # app source + deps");
                println!("  sudo mkdir -p /opt/{app_name} && sudo rsync -a --exclude node_modules --exclude .pylon ./ /opt/{app_name}/");
                println!("  cd /opt/{app_name} && sudo bun install");
                println!("  # service");
                println!("  sudo useradd --system --home /var/lib/pylon pylon");
                println!("  sudo mkdir -p /var/lib/pylon && sudo chown pylon: /var/lib/pylon");
                println!("  sudo cp {out_dir}/pylon.service /etc/systemd/system/");
                println!("  sudo systemctl enable --now pylon");
            }
            DeployTarget::Manifest => {
                println!("To run the server:");
                println!("  pylon dev {manifest_path}");
                println!();
                println!("For containerized deployment, use --target:");
                println!("  pylon deploy --target docker     # Dockerfile");
                println!("  pylon deploy --target fly        # Dockerfile + fly.toml");
                println!("  pylon deploy --target compose    # docker-compose.yml + Dockerfile");
                println!(
                    "  pylon deploy --target workers    # Cloudflare wrangler.toml (experimental)"
                );
                println!("  pylon deploy --target systemd    # systemd unit for VPS install");
            }
        }
    }

    ExitCode::Ok
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Write a Docker-ecosystem artifact at the project root. Regenerates files
/// from a previous run (identified by GENERATED_MARKER) but never clobbers a
/// hand-written file with the same name.
fn write_root_artifact(
    root: &std::path::Path,
    filename: &str,
    content: &str,
    json_mode: bool,
    generated_files: &mut Vec<String>,
) {
    let path = root.join(filename);
    if let Ok(existing) = std::fs::read_to_string(&path) {
        if !existing.contains(GENERATED_MARKER) {
            print_diagnostics(
                &[Diagnostic {
                    severity: Severity::Warning,
                    code: "DEPLOY_FILE_EXISTS".into(),
                    message: format!(
                        "{filename} already exists and wasn't generated by pylon — left unchanged"
                    ),
                    span: None,
                    hint: Some(format!(
                        "delete or rename {filename} and re-run to regenerate it"
                    )),
                }],
                json_mode,
            );
            return;
        }
    }
    if let Err(e) = std::fs::write(&path, content) {
        print_diagnostics(
            &[Diagnostic {
                severity: Severity::Warning,
                code: "DEPLOY_WRITE_FAILED".into(),
                message: format!("Could not write {filename}: {e}"),
                span: None,
                hint: None,
            }],
            json_mode,
        );
        return;
    }
    generated_files.push(format!("{filename} (project root)"));
}

/// Write a file into the output directory, printing a diagnostic on failure.
fn write_or_fail(out_path: &std::path::Path, filename: &str, content: &str, json_mode: bool) {
    let path = out_path.join(filename);
    if let Err(e) = std::fs::write(&path, content) {
        print_diagnostics(
            &[Diagnostic {
                severity: Severity::Warning,
                code: "DEPLOY_WRITE_FAILED".into(),
                message: format!("Could not write {filename}: {e}"),
                span: None,
                hint: None,
            }],
            json_mode,
        );
    }
}

/// Sanitize a manifest name into a valid Fly.io app name.
///
/// Fly app names must be lowercase alphanumeric with hyphens, no underscores
/// or spaces.
fn sanitize_app_name(name: &str) -> String {
    name.to_lowercase()
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '-' {
                c
            } else {
                '-'
            }
        })
        .collect()
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn dockerfile_runs_the_app_on_the_runtime_image() {
        let df = generate_dockerfile();
        // Pinned to the generating CLI's own version, not :latest.
        assert!(df.contains(&format!(
            "FROM ghcr.io/pylonsync/pylon:{}",
            env!("CARGO_PKG_VERSION")
        )));
        assert!(df.contains("bun install"));
        assert!(df.contains(GENERATED_MARKER));
        // Regression: the old generator cargo-built the user's TS app
        // (impossible) and ran `pylon dev --once`, which validates and
        // exits — the container died instantly.
        assert!(!df.contains("cargo build"));
        assert!(!df.contains("\"dev\""));
        assert!(!df.contains("--once"));
    }

    #[test]
    fn dockerignore_excludes_local_state() {
        let di = generate_dockerignore();
        assert!(di.contains("node_modules"));
        assert!(di.contains(".pylon"));
        assert!(di.contains(GENERATED_MARKER));
    }

    #[test]
    fn fly_toml_contains_app_name_and_port() {
        let toml = generate_fly_toml("my-app");
        assert!(toml.contains("app = \"my-app\""));
        assert!(toml.contains("internal_port = 4321"));
        assert!(toml.contains("force_https = true"));
        assert!(toml.contains("primary_region = \"iad\""));
        assert!(toml.contains("destination = \"/data\""));
    }

    #[test]
    fn docker_compose_contains_services() {
        let dc = generate_docker_compose();
        assert!(dc.contains("services:"));
        assert!(dc.contains("postgres:16"));
        assert!(dc.contains("DATABASE_URL=postgres://pylon:pylon@db:5432/pylon"));
        assert!(dc.contains("PYLON_ADMIN_TOKEN"));
        assert!(dc.contains("pylon-data:/data"));
        assert!(dc.contains("pgdata:"));
    }

    #[test]
    fn sanitize_app_name_handles_spaces_and_underscores() {
        assert_eq!(sanitize_app_name("My App"), "my-app");
        assert_eq!(sanitize_app_name("my_app"), "my-app");
        assert_eq!(sanitize_app_name("already-good"), "already-good");
        assert_eq!(sanitize_app_name("UPPER"), "upper");
    }

    #[test]
    fn deploy_target_parsing() {
        assert_eq!(DeployTarget::from_arg("docker"), Some(DeployTarget::Docker));
        assert_eq!(DeployTarget::from_arg("fly"), Some(DeployTarget::Fly));
        assert_eq!(
            DeployTarget::from_arg("compose"),
            Some(DeployTarget::Compose)
        );
        assert_eq!(
            DeployTarget::from_arg("workers"),
            Some(DeployTarget::Workers)
        );
        assert_eq!(
            DeployTarget::from_arg("systemd"),
            Some(DeployTarget::Systemd)
        );
        assert_eq!(DeployTarget::from_arg("unknown"), None);
    }

    #[test]
    fn wrangler_toml_contains_required_fields() {
        let w = generate_wrangler_toml("my-app");
        assert!(w.contains("name = \"my-app\""));
        assert!(w.contains("d1_databases"));
        assert!(w.contains("PYLON_DB"));
        assert!(w.contains("compatibility_date"));
    }

    #[test]
    fn systemd_unit_contains_hardening() {
        let u = generate_systemd_unit("pylon-prod");
        assert!(u.contains("ExecStart=/usr/local/bin/pylon start app.ts"));
        assert!(u.contains("WorkingDirectory=/opt/pylon-prod"));
        assert!(u.contains("NoNewPrivileges=true"));
        assert!(u.contains("ProtectSystem=strict"));
        assert!(u.contains("WantedBy=multi-user.target"));
        // Regression: the unit used to launch the hot-reload dev server
        // (`pylon dev`) in production.
        assert!(!u.contains("pylon dev"));
    }

    #[test]
    fn root_artifacts_never_clobber_hand_written_files() {
        let dir = std::env::temp_dir().join(format!("pylon-deploy-test-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let mut generated: Vec<String> = vec![];

        // A hand-written Dockerfile (no marker) must survive.
        std::fs::write(dir.join("Dockerfile"), "FROM scratch\n").unwrap();
        write_root_artifact(
            &dir,
            "Dockerfile",
            &generate_dockerfile(),
            true,
            &mut generated,
        );
        assert_eq!(
            std::fs::read_to_string(dir.join("Dockerfile")).unwrap(),
            "FROM scratch\n"
        );
        assert!(generated.is_empty());

        // A previously generated file (marker present) is regenerated.
        std::fs::write(dir.join("fly.toml"), format!("# {GENERATED_MARKER}\nstale")).unwrap();
        write_root_artifact(
            &dir,
            "fly.toml",
            &generate_fly_toml("x"),
            true,
            &mut generated,
        );
        assert!(std::fs::read_to_string(dir.join("fly.toml"))
            .unwrap()
            .contains("app = \"x\""));
        assert_eq!(generated.len(), 1);

        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn docker_compose_has_depends_on() {
        let dc = generate_docker_compose();
        assert!(dc.contains("depends_on:"));
    }
}
