// Sample data for a fresh install, so the dashboard shows what a working
// assistant looks like before the first real text arrives. Every row is
// flagged `demo: true`, labeled "Sample" in the UI, and removed by clearDemo.
// The assistant lines are written by hand, not generated by a model.

export interface DemoMessage {
  /** Minutes before now. */
  ago: number;
  from: "them" | "assistant";
  text: string;
}

export interface DemoThread {
  handle: string;
  displayName: string | null;
  status: "allowed" | "unknown";
  messages: DemoMessage[];
  notes?: string[];
  reminder?: { inMinutes: number; text: string };
}

export const DEMO_THREADS: DemoThread[] = [
  {
    handle: "+15125550148",
    displayName: "Maya Chen",
    status: "allowed",
    notes: ["Allergic to cashews", "Daughter Ruby has soccer Saturdays at 9:30, Zilker field 4"],
    reminder: { inMinutes: 60 * 20, text: "Morning Maya, Ruby's soccer starts at 9:30 at Zilker field 4." },
    messages: [
      { ago: 180, from: "them", text: "hey, for the dinner thursday, remember I can't do cashews" },
      {
        ago: 179,
        from: "assistant",
        text: "Saved: no cashews. Jordan will see it before Thursday, and I'll keep it in mind next time food comes up.",
      },
      { ago: 42, from: "them", text: "can you remind me tomorrow morning about Ruby's soccer? starts 9:30 at Zilker, field 4" },
      {
        ago: 41,
        from: "assistant",
        text: "Done. I'll text you tomorrow at 8:00 AM: Ruby's soccer at 9:30, Zilker field 4.",
      },
      { ago: 40, from: "them", text: "you're the best" },
      { ago: 39, from: "assistant", text: "Happy to help. Good luck to Ruby." },
    ],
  },
  {
    handle: "+15125550163",
    displayName: "Dad",
    status: "allowed",
    notes: ["New gate code is 4417"],
    messages: [
      { ago: 60 * 26, from: "them", text: "Tell Jordan the gate code changed to 4417" },
      {
        ago: 60 * 26 - 1,
        from: "assistant",
        text: "Got it, gate code 4417. I saved it, and Jordan sees this conversation.",
      },
      { ago: 60 * 25, from: "them", text: "What was the code again?" },
      { ago: 60 * 25 - 1, from: "assistant", text: "4417." },
    ],
  },
  {
    handle: "+17375550191",
    displayName: null,
    status: "unknown",
    messages: [{ ago: 15, from: "them", text: "Hi is this Jordan? Got your number from the climbing gym" }],
  },
];
