/**
 * Typed database client — narrow pylon's untyped `db` object using your
 * generated `AppSchema` (from `pylon codegen client`).
 *
 * @example
 * ```ts
 * // src/pylon.client.ts (generated by `pylon codegen client`)
 * export interface AppSchema {
 *   entities: { Todo: Todo; User: User };
 *   functions: {
 *     placeBid: { input: { lotId: string; amount: number }; output: { accepted: boolean } };
 *   };
 *   queries: {};
 * }
 *
 * // src/db.ts
 * import { createTypedDb } from "@pylonsync/react";
 * import type { AppSchema } from "./pylon.client";
 * export const db = createTypedDb<AppSchema>();
 *
 * // Components get full type safety:
 * const { data } = db.useQuery("Todo");         // data: Todo[]
 * const { data: user } = db.useQueryOne("User", "u_1"); // user: User | null
 * const bid = db.useMutation("placeBid");        // typed args + result
 * await bid.mutate({ lotId: "x", amount: 150 }); // TS checks input type
 * ```
 */

import type { Row } from "@pylonsync/sync";
import { db as untypedDb } from "./db";
import type {
  QueryOptions,
  UseQueryReturn,
  UseQueryOneReturn,
  UseMutationReturn,
  UseInfiniteQueryReturn,
} from "./hooks";

// ---------------------------------------------------------------------------
// Schema shape
// ---------------------------------------------------------------------------

/**
 * Shape of the generated `AppSchema` interface.
 *
 * The CLI's `client_codegen` emits a type matching this shape. Consumers
 * never construct `AppSchema` manually.
 */
export interface AgentDBSchema {
  entities: Record<string, unknown>;
  functions: Record<string, { input: unknown; output: unknown }>;
  queries: Record<string, { input: unknown; output: unknown }>;
}

// ---------------------------------------------------------------------------
// TypedDb — mirrors `db` but with generics keyed on the schema
// ---------------------------------------------------------------------------

export interface TypedDb<S extends AgentDBSchema> {
  /** Live query with type inferred from the schema. */
  useQuery<K extends keyof S["entities"]>(
    entity: K,
    options?: QueryOptions
  ): UseQueryReturn<S["entities"][K]>;

  /** Live single-row query. */
  useQueryOne<K extends keyof S["entities"]>(
    entity: K,
    id: string
  ): UseQueryOneReturn<S["entities"][K]>;

  /** Server-side function call with typed input/output. */
  useMutation<K extends keyof S["functions"]>(
    fnName: K
  ): UseMutationReturn<S["functions"][K]["input"], S["functions"][K]["output"]>;

  /** Paginated live query. */
  useInfiniteQuery<K extends keyof S["entities"]>(
    entity: K,
    options?: { pageSize?: number }
  ): UseInfiniteQueryReturn<S["entities"][K]>;

  /** Call a server-side function directly (outside React). */
  fn<K extends keyof S["functions"]>(
    name: K,
    args: S["functions"][K]["input"]
  ): Promise<S["functions"][K]["output"]>;

  /** Insert a row (optimistic). */
  insert<K extends keyof S["entities"]>(
    entity: K,
    data: Partial<S["entities"][K]>
  ): unknown;

  /** Update a row (optimistic). */
  update<K extends keyof S["entities"]>(
    entity: K,
    id: string,
    data: Partial<S["entities"][K]>
  ): unknown;

  /** Delete a row (optimistic). */
  delete<K extends keyof S["entities"]>(entity: K, id: string): unknown;

  /** Underlying untyped db (escape hatch). */
  readonly untyped: typeof untypedDb;
}

/**
 * Create a typed client from a generated `AppSchema`.
 *
 * At runtime this is literally the same object as `db`; types are narrowed
 * at compile time via generics.
 */
export function createTypedDb<S extends AgentDBSchema>(): TypedDb<S> {
  const d = untypedDb as unknown as {
    useQuery: <T>(entity: string, options?: QueryOptions) => UseQueryReturn<T>;
    useQueryOne: <T>(entity: string, id: string) => UseQueryOneReturn<T>;
    useMutation: <A, R>(fn: string) => UseMutationReturn<A, R>;
    useInfiniteQuery: <T>(
      entity: string,
      options?: { pageSize?: number }
    ) => UseInfiniteQueryReturn<T>;
    fn: <R>(name: string, args?: Record<string, unknown>) => Promise<R>;
    insert: (entity: string, data: Row) => unknown;
    update: (entity: string, id: string, data: Partial<Row>) => unknown;
    delete: (entity: string, id: string) => unknown;
  };

  return {
    useQuery: ((entity, options) =>
      d.useQuery(entity as string, options)) as TypedDb<S>["useQuery"],
    useQueryOne: ((entity, id) =>
      d.useQueryOne(entity as string, id)) as TypedDb<S>["useQueryOne"],
    useMutation: ((fnName) =>
      d.useMutation(fnName as string)) as TypedDb<S>["useMutation"],
    useInfiniteQuery: ((entity, options) =>
      d.useInfiniteQuery(entity as string, options)) as TypedDb<S>["useInfiniteQuery"],
    fn: ((name, args) =>
      d.fn(name as string, args as Record<string, unknown>)) as TypedDb<S>["fn"],
    insert: ((entity, data) =>
      d.insert(entity as string, data as Row)) as TypedDb<S>["insert"],
    update: ((entity, id, data) =>
      d.update(entity as string, id, data as Partial<Row>)) as TypedDb<S>["update"],
    delete: ((entity, id) =>
      d.delete(entity as string, id)) as TypedDb<S>["delete"],
    untyped: untypedDb,
  };
}
